### ISSUE TITLE
Для чего хранить в проекте файлы бутстрапа, если можно ограничиться ссылкой на cdn

### ISSUE THREAD

**Issue by SuperLalka** [igorKichkar/bootstrap-page#1]
Почитай подробности здесь https://bootstrap-4.ru/docs/4.5/getting-started/introduction/

Образец здесь 
https://github.com/SuperLalka/shop-allhere/blob/47baa156718fedc49922f61fe05aeb435f7eaa40/app_shop/templates/base_generic.html#L15-L25

**Comment by igorKichkar** [comment]
> Почитай подробности здесь https://bootstrap-4.ru/docs/4.5/getting-started/introduction/
> 
> Образец здесь
> https://github.com/SuperLalka/shop-allhere/blob/47baa156718fedc49922f61fe05aeb435f7eaa40/app_shop/templates/base_generic.html#L15-L2

**Comment by igorKichkar** [comment]
> > Почитай подробности здесь https://bootstrap-4.ru/docs/4.5/getting-started/introduction/
> > Образец здесь
> > https://github.com/SuperLalka/shop-allhere/blob/47baa156718fedc49922f61fe05aeb435f7eaa40/app_shop/templates/base_generic.html#L15-L2

я сразу так и делал, потом захотелось какой-то автономности), решил подключить таким образом
